baseURL = 'https://phangelim.github.io/'
locale = 'en-us'
title = 'phangelim'
theme = 'hugo-coder'

[pagination]
pagerSize = 20

[params]
author = "phangelim"

colorScheme = "auto"
hidecolorSchemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/phangelim/"

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/pedro-henrique-lima-coelho-8256a1387/?locale=en"

#Menu links
[[menu.main]]
name = "Posts"
weight = 1 
url = "posts/"

[[menu.main]]
name = "About"
weight = 2 
url = "about/"

[[menu.main]]
name = "Contact"
weight = 3 
url = "contact/"


